cmake_policy(SET CMP0135 NEW)

message(STATUS "Including oneDNNConfig.cmake - building oneDNN")


set(ONEDNN_CPU_RUNTIME "OMP" CACHE STRING "oneDNN CPU runtime")
set(DNNL_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(DNNL_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(DNNL_BUILD_BENCHMARKS OFF CACHE BOOL "" FORCE)
set(DNNL_BUILD_DOCUMENTATION OFF CACHE BOOL "" FORCE)
set(DNNL_ENABLE_JIT_PROFILING OFF CACHE BOOL "" FORCE)
set(DNNL_LIBRARY_TYPE "SHARED" CACHE STRING "" FORCE)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

# Fetch oneDNN
FetchContent_Declare(
  dnnl
  URL          "${CMAKE_CURRENT_SOURCE_DIR}/vendor/oneDNN-3.8.1.zip"
  URL_HASH     SHA256=153a48898ea8cd40085d32fa725e5e8cadc6b08c75470e6dac54d60d32dcb8df
)

FetchContent_MakeAvailable(dnnl)